serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'frontend-external-feed-generator'
        metrics_path: /prometheus
        scheme: http
        static_configs:
          - targets: ['frontend-external-feed-generator.stable-int.svc.cluster.local:9034']

# Disable all extras
prometheus-node-exporter:
  enabled: false

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-pushgateway:
  enabled: false
